<?php

namespace App\Support;

class Countries
{
    public static function all(): array
    {
        return array_merge(
            self::americas(),
            self::europe(),
            self::africa(),
            self::asia(),
            self::oceania()
        );
    }

    public static function americas(): array
    {
        return [
            'US' => 'United States',
            'CA' => 'Canada',
            'MX' => 'Mexico',
            'GT' => 'Guatemala',
            'BZ' => 'Belize',
            'HN' => 'Honduras',
            'SV' => 'El Salvador',
            'NI' => 'Nicaragua',
            'CR' => 'Costa Rica',
            'PA' => 'Panama',
            'CU' => 'Cuba',
            'JM' => 'Jamaica',
            'HT' => 'Haiti',
            'DO' => 'Dominican Republic',
            'PR' => 'Puerto Rico',
            'TT' => 'Trinidad and Tobago',
            'BB' => 'Barbados',
            'LC' => 'Saint Lucia',
            'DM' => 'Dominica',
            'GD' => 'Grenada',
            'VC' => 'Saint Vincent and the Grenadines',
            'AG' => 'Antigua and Barbuda',
            'KN' => 'Saint Kitts and Nevis',
            'BS' => 'Bahamas',
            'CO' => 'Colombia',
            'VE' => 'Venezuela',
            'GY' => 'Guyana',
            'SR' => 'Suriname',
            'EC' => 'Ecuador',
            'PE' => 'Peru',
            'BR' => 'Brazil',
            'BO' => 'Bolivia',
            'PY' => 'Paraguay',
            'CL' => 'Chile',
            'AR' => 'Argentina',
            'UY' => 'Uruguay',
        ];
    }

    public static function europe(): array
    {
        return [
            'GB' => 'United Kingdom',
            'IE' => 'Ireland',
            'FR' => 'France',
            'DE' => 'Germany',
            'NL' => 'Netherlands',
            'BE' => 'Belgium',
            'LU' => 'Luxembourg',
            'CH' => 'Switzerland',
            'AT' => 'Austria',
            'IT' => 'Italy',
            'ES' => 'Spain',
            'PT' => 'Portugal',
            'GR' => 'Greece',
            'PL' => 'Poland',
            'CZ' => 'Czech Republic',
            'SK' => 'Slovakia',
            'HU' => 'Hungary',
            'RO' => 'Romania',
            'BG' => 'Bulgaria',
            'HR' => 'Croatia',
            'SI' => 'Slovenia',
            'RS' => 'Serbia',
            'BA' => 'Bosnia and Herzegovina',
            'ME' => 'Montenegro',
            'MK' => 'North Macedonia',
            'AL' => 'Albania',
            'XK' => 'Kosovo',
            'SE' => 'Sweden',
            'NO' => 'Norway',
            'DK' => 'Denmark',
            'FI' => 'Finland',
            'IS' => 'Iceland',
            'EE' => 'Estonia',
            'LV' => 'Latvia',
            'LT' => 'Lithuania',
            'UA' => 'Ukraine',
            'BY' => 'Belarus',
            'MD' => 'Moldova',
            'RU' => 'Russia',
            'MT' => 'Malta',
            'CY' => 'Cyprus',
            'TR' => 'Turkey',
            'GE' => 'Georgia',
            'AM' => 'Armenia',
            'AZ' => 'Azerbaijan',
        ];
    }

    public static function africa(): array
    {
        return [
            'MA' => 'Morocco',
            'DZ' => 'Algeria',
            'TN' => 'Tunisia',
            'LY' => 'Libya',
            'EG' => 'Egypt',
            'SD' => 'Sudan',
            'SS' => 'South Sudan',
            'ET' => 'Ethiopia',
            'ER' => 'Eritrea',
            'DJ' => 'Djibouti',
            'SO' => 'Somalia',
            'KE' => 'Kenya',
            'UG' => 'Uganda',
            'TZ' => 'Tanzania',
            'RW' => 'Rwanda',
            'BI' => 'Burundi',
            'CD' => 'Democratic Republic of Congo',
            'CG' => 'Republic of Congo',
            'GA' => 'Gabon',
            'GQ' => 'Equatorial Guinea',
            'CM' => 'Cameroon',
            'CF' => 'Central African Republic',
            'TD' => 'Chad',
            'NE' => 'Niger',
            'NG' => 'Nigeria',
            'BJ' => 'Benin',
            'TG' => 'Togo',
            'GH' => 'Ghana',
            'CI' => 'Ivory Coast',
            'LR' => 'Liberia',
            'SL' => 'Sierra Leone',
            'GN' => 'Guinea',
            'GW' => 'Guinea-Bissau',
            'SN' => 'Senegal',
            'GM' => 'Gambia',
            'MR' => 'Mauritania',
            'ML' => 'Mali',
            'BF' => 'Burkina Faso',
            'CV' => 'Cape Verde',
            'ZA' => 'South Africa',
            'NA' => 'Namibia',
            'BW' => 'Botswana',
            'ZW' => 'Zimbabwe',
            'ZM' => 'Zambia',
            'MW' => 'Malawi',
            'MZ' => 'Mozambique',
            'MG' => 'Madagascar',
            'MU' => 'Mauritius',
            'SC' => 'Seychelles',
            'AO' => 'Angola',
            'SZ' => 'Eswatini',
            'LS' => 'Lesotho',
        ];
    }

    public static function asia(): array
    {
        return [
            'CN' => 'China',
            'JP' => 'Japan',
            'KR' => 'South Korea',
            'KP' => 'North Korea',
            'TW' => 'Taiwan',
            'MN' => 'Mongolia',
            'HK' => 'Hong Kong',
            'MO' => 'Macau',
            'IN' => 'India',
            'PK' => 'Pakistan',
            'BD' => 'Bangladesh',
            'LK' => 'Sri Lanka',
            'NP' => 'Nepal',
            'BT' => 'Bhutan',
            'MM' => 'Myanmar',
            'TH' => 'Thailand',
            'VN' => 'Vietnam',
            'LA' => 'Laos',
            'KH' => 'Cambodia',
            'MY' => 'Malaysia',
            'SG' => 'Singapore',
            'ID' => 'Indonesia',
            'PH' => 'Philippines',
            'BN' => 'Brunei',
            'TL' => 'Timor-Leste',
            'SA' => 'Saudi Arabia',
            'AE' => 'United Arab Emirates',
            'QA' => 'Qatar',
            'KW' => 'Kuwait',
            'BH' => 'Bahrain',
            'OM' => 'Oman',
            'YE' => 'Yemen',
            'IQ' => 'Iraq',
            'IR' => 'Iran',
            'SY' => 'Syria',
            'LB' => 'Lebanon',
            'JO' => 'Jordan',
            'IL' => 'Israel',
            'PS' => 'Palestine',
            'AF' => 'Afghanistan',
            'KZ' => 'Kazakhstan',
            'UZ' => 'Uzbekistan',
            'TM' => 'Turkmenistan',
            'TJ' => 'Tajikistan',
            'KG' => 'Kyrgyzstan',
        ];
    }

    public static function oceania(): array
    {
        return [
            'AU' => 'Australia',
            'NZ' => 'New Zealand',
            'PG' => 'Papua New Guinea',
            'FJ' => 'Fiji',
            'SB' => 'Solomon Islands',
            'VU' => 'Vanuatu',
            'NC' => 'New Caledonia',
            'PF' => 'French Polynesia',
            'WS' => 'Samoa',
            'TO' => 'Tonga',
            'FM' => 'Micronesia',
            'PW' => 'Palau',
            'MH' => 'Marshall Islands',
            'KI' => 'Kiribati',
            'NR' => 'Nauru',
            'TV' => 'Tuvalu',
            'GU' => 'Guam',
        ];
    }
}
